# GitHub Pages Configuration for CVForge Documentation
title: CVForge Documentation
description: Complete guide to using CVForge browser extension and Personal Access Tokens
author: CVForge Team
baseurl: "/docs"
url: "https://yourusername.github.io"

# GitHub Pages settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation
navigation:
  - title: Home
    url: /
  - title: Getting Started
    url: /getting-started/
  - title: User Guides
    url: /user-guides/
  - title: Troubleshooting
    url: /troubleshooting/
  - title: FAQ
    url: /faq/

# Theme settings
theme: minima

# Markdown settings
markdown: kramdown
highlighter: rouge

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
