# GitHub Pages Configuration for CVForge Documentation
title: CVForge Documentation
description: Complete guide to using CVForge web app and browser extension
author: CVForge Team
baseurl: ""
url: "https://baloghp.github.io"

# GitHub Pages settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Theme settings - using just-the-docs for better documentation layout
remote_theme: just-the-docs/just-the-docs
minimal_mistakes_skin: default

# Navigation
header_pages:
  - index.md
  - extension/index.md

# Just the Docs theme settings
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_token_threshold: 150
  rel_url: true
  index_only: false

# Color scheme
color_scheme: light

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - deployment/
