# GitHub Pages Configuration for CVForge Documentation
title: CVForge Documentation
description: Complete guide to using CVForge web app and browser extension
author: CVForge Team
baseurl: ""
url: "https://baloghp.github.io"

# GitHub Pages settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Theme settings - using minimal theme for GitHub Pages compatibility
theme: minima

# Minima theme settings
minima:
  social:
    - name: github
      username: baloghp
    - name: twitter
      username: cvforge
  skin: light

# Navigation
header_pages:
  - index.md
  - extension/index.md

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - deployment/
